import { useDeferredValue, useEffect, useMemo, useState } from 'react';
import { Download, Eye, FileText, FolderOpen, Search } from 'lucide-react';
import type { ReportExportAuditPayload } from '../types/audit';
import type { AuthUser } from '../types/auth';
import type { StoredReport } from '../types/reports';
import { useLanguage } from '../i18n';
import { openPrintableReport } from '../utils/reportExport';

interface ReportsProps {
  currentUser: AuthUser;
  initialProjectKey?: string;
  initialProjectLabel?: string;
  globalSearch?: { query: string; nonce: number };
}

const REPORTS_TEXT = {
  en: {
    history: 'Report History',
    title: 'Technical Reports Archive',
    description: 'Reopen previously generated spectrophotometry reports without rebuilding the calculation.',
    adminScope: 'Administrators can review the complete shared archive.',
    userScope: 'This view is scoped to the reports generated from your account.',
    searchPlaceholder: 'Search reports, projects, compounds, CAS or dates...',
    selectProject: 'Select a project',
    reports: 'reports',
    lastResult: 'Last result',
    loading: 'Loading saved reports...',
    loadError: 'Unable to load saved reports right now.',
    noReports: 'No completed project reports found yet.',
    selectProjectEmpty: 'Select a project above to open its generated results.',
    noProjectReports: 'No reports found inside this project for the current search.',
    printPdf: 'Print PDF report',
    openPreview: 'Open report preview',
    savedSnapshot: 'Saved Snapshot',
    generatedBy: 'Generated by',
    generatedAt: 'Generated at',
    absorbance: 'Absorbance',
    lambdaMax: 'Lambda max',
    solvent: 'Solvent',
    source: 'Source',
    pathLength: 'Path length',
    concentration: 'Concentration',
    stored: 'Stored'
  },
  pt: {
    history: 'Histórico de Relatórios',
    title: 'Arquivo de Relatórios Técnicos',
    description: 'Reabra relatórios de espectrofotometria gerados anteriormente sem refazer o cálculo.',
    adminScope: 'Administradores podem revisar o arquivo compartilhado completo.',
    userScope: 'Esta visualização mostra apenas os relatórios gerados pela sua conta.',
    searchPlaceholder: 'Pesquisar relatórios, projetos, compostos, CAS ou datas...',
    selectProject: 'Selecione um projeto',
    reports: 'relatórios',
    lastResult: 'Último resultado',
    loading: 'Carregando relatórios salvos...',
    loadError: 'Não foi possível carregar os relatórios salvos agora.',
    noReports: 'Ainda não há relatórios de projeto concluídos.',
    selectProjectEmpty: 'Selecione um projeto acima para abrir seus resultados gerados.',
    noProjectReports: 'Nenhum relatório encontrado neste projeto para a busca atual.',
    printPdf: 'Imprimir relatório PDF',
    openPreview: 'Abrir prévia do relatório',
    savedSnapshot: 'Snapshot Salvo',
    generatedBy: 'Gerado por',
    generatedAt: 'Gerado em',
    absorbance: 'Absorbância',
    lambdaMax: 'Lambda max',
    solvent: 'Solvente',
    source: 'Fonte',
    pathLength: 'Caminho óptico',
    concentration: 'Concentração',
    stored: 'Armazenado'
  },
  es: {
    history: 'Historial de Informes',
    title: 'Archivo de Informes Técnicos',
    description: 'Reabre informes de espectrofotometría generados anteriormente sin reconstruir el cálculo.',
    adminScope: 'Los administradores pueden revisar el archivo compartido completo.',
    userScope: 'Esta vista muestra solo los informes generados desde tu cuenta.',
    searchPlaceholder: 'Buscar informes, proyectos, compuestos, CAS o fechas...',
    selectProject: 'Selecciona un proyecto',
    reports: 'informes',
    lastResult: 'Último resultado',
    loading: 'Cargando informes guardados...',
    loadError: 'No se pueden cargar los informes guardados en este momento.',
    noReports: 'Aún no hay informes de proyecto completados.',
    selectProjectEmpty: 'Selecciona un proyecto arriba para abrir sus resultados generados.',
    noProjectReports: 'No se encontraron informes en este proyecto para la búsqueda actual.',
    printPdf: 'Imprimir informe PDF',
    openPreview: 'Abrir vista previa del informe',
    savedSnapshot: 'Snapshot Guardado',
    generatedBy: 'Generado por',
    generatedAt: 'Generado el',
    absorbance: 'Absorbancia',
    lambdaMax: 'Lambda max',
    solvent: 'Solvente',
    source: 'Fuente',
    pathLength: 'Longitud de camino',
    concentration: 'Concentración',
    stored: 'Guardado'
  }
};

function formatDateTime(value: string) {
  return new Date(value).toLocaleString('pt-BR');
}

function getDateSearchTerms(value: string) {
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return [value];
  }

  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const year = String(date.getFullYear());
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');

  return [
    value,
    formatDateTime(value),
    `${day}/${month}/${year}`,
    `${day}/${month}`,
    `${month}/${year}`,
    `${year}-${month}-${day}`,
    `${year}/${month}/${day}`,
    `${day}-${month}-${year}`,
    `${day}.${month}.${year}`,
    `${hours}:${minutes}`
  ];
}

function formatNumber(value: number) {
  return new Intl.NumberFormat('pt-BR', {
    maximumFractionDigits: 4
  }).format(value);
}

function formatWavelengthMax(value: string) {
  const trimmed = value.trim();

  if (!trimmed || trimmed === 'N/A') {
    return 'N/A';
  }

  return /\bnm\b/i.test(trimmed) || /nanometer/i.test(trimmed)
    ? trimmed.replace(/\bnm\b/gi, 'nanometers (nm)')
    : `${trimmed} nanometers (nm)`;
}

function getReportProject(report: StoredReport) {
  if (report.projectId || report.projectName) {
    const label = report.projectName || report.projectId || 'Project';
    return {
      key: report.projectId || label.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
      label
    };
  }

  const [rawProject] = report.compoundName.split(' - ');
  const label = rawProject?.trim() || report.compoundName || 'Not identified';
  const normalizedLabel = label.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const key = report.casId && report.casId !== 'N/A' ? report.casId : normalizedLabel || label;

  return { key, label };
}

function normalizeProjectKey(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function projectMatchesKey(project: { key: string; label: string }, key: string) {
  const normalizedKey = normalizeProjectKey(key);

  return (
    project.key === key
    || normalizeProjectKey(project.key) === normalizedKey
    || normalizeProjectKey(project.label) === normalizedKey
  );
}

function projectMatchesSearch(project: { key: string; label: string }, search: string) {
  const normalizedSearch = search.trim().toLowerCase();
  const normalizedProjectSearch = normalizeProjectKey(search);

  if (!normalizedSearch) {
    return true;
  }

  return [
    project.key,
    project.label,
    normalizeProjectKey(project.key),
    normalizeProjectKey(project.label)
  ].some((value) => (
    value.toLowerCase().includes(normalizedSearch)
    || value.toLowerCase().includes(normalizedProjectSearch)
  ));
}

function getReportAnalysis(report: StoredReport) {
  const [, ...analysisParts] = report.compoundName.split(' - ');
  return analysisParts.join(' - ').trim() || report.source || 'Analytical report';
}

export default function Reports({ currentUser, initialProjectKey, initialProjectLabel, globalSearch }: ReportsProps) {
  const { language } = useLanguage();
  const text = REPORTS_TEXT[language];
  const [query, setQuery] = useState('');
  const deferredQuery = useDeferredValue(query);
  const [projectQuery, setProjectQuery] = useState(initialProjectLabel ?? initialProjectKey ?? '');
  const deferredProjectQuery = useDeferredValue(projectQuery);
  const [reports, setReports] = useState<StoredReport[]>([]);
  const [selectedProjectKey, setSelectedProjectKey] = useState(initialProjectKey ?? '');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeReportId, setActiveReportId] = useState<number | null>(null);

  useEffect(() => {
    if (!globalSearch) return;
    setQuery(globalSearch.query);
  }, [globalSearch?.nonce]);

  useEffect(() => {
    const controller = new AbortController();

    async function loadReports() {
      setIsLoading(true);
      setError(null);

      try {
        const response = await fetch('/api/reports', {
          credentials: 'include',
          signal: controller.signal
        });

        if (!response.ok) {
          throw new Error(`Request failed with status ${response.status}`);
        }

        const payload = (await response.json()) as { reports: StoredReport[] };
        setReports(payload.reports);
      } catch (loadError) {
        if (loadError instanceof DOMException && loadError.name === 'AbortError') {
          return;
        }

        console.error('Failed to load reports:', loadError);
        setError(text.loadError);
      } finally {
        setIsLoading(false);
      }
    }

    void loadReports();

    return () => controller.abort();
  }, [text.loadError]);

  const projectOptions = useMemo(() => {
    const projects = new Map<string, { key: string; label: string; reports: number; lastReportAt: string }>();

    reports.forEach((report) => {
      const project = getReportProject(report);
      const current = projects.get(project.key);

      if (!current) {
        projects.set(project.key, {
          ...project,
          reports: 1,
          lastReportAt: report.createdAt
        });
        return;
      }

      projects.set(project.key, {
        ...current,
        reports: current.reports + 1,
        lastReportAt: new Date(report.createdAt) > new Date(current.lastReportAt)
          ? report.createdAt
          : current.lastReportAt
      });
    });

    return Array.from(projects.values()).sort((left, right) => (
      new Date(right.lastReportAt).getTime() - new Date(left.lastReportAt).getTime()
    ));
  }, [reports]);

  useEffect(() => {
    if (!initialProjectKey && !initialProjectLabel) {
      setSelectedProjectKey('');
      setProjectQuery('');
      return;
    }

    if (projectOptions.length === 0) {
      setSelectedProjectKey(initialProjectKey ?? '');
      setProjectQuery(initialProjectLabel ?? initialProjectKey ?? '');
      return;
    }

    const normalizedInitialLabel = initialProjectLabel ? normalizeProjectKey(initialProjectLabel) : '';
    const matchingProject = projectOptions.find((project) => (
      (initialProjectKey ? projectMatchesKey(project, initialProjectKey) : false)
      || normalizeProjectKey(project.label) === normalizedInitialLabel
    ));

    setSelectedProjectKey(matchingProject?.key ?? initialProjectKey ?? '');
    setProjectQuery(matchingProject?.label ?? initialProjectLabel ?? initialProjectKey ?? '');
  }, [initialProjectKey, initialProjectLabel, projectOptions]);

  const filteredProjectOptions = useMemo(() => (
    projectOptions.filter((project) => projectMatchesSearch(project, deferredProjectQuery))
  ), [deferredProjectQuery, projectOptions]);

  const visibleReports = useMemo(() => {
    const normalizedQuery = deferredQuery.trim().toLowerCase();
    const normalizedProjectQuery = deferredProjectQuery.trim();

    return reports.filter((report) => {
      const project = getReportProject(report);
      if (selectedProjectKey && project.key !== selectedProjectKey) return false;
      if (!selectedProjectKey && normalizedProjectQuery && !projectMatchesSearch(project, normalizedProjectQuery)) return false;
      if (!normalizedQuery) return true;

      return [
        report.reportId,
        report.projectId || '',
        report.projectName || '',
        project.key,
        project.label,
        report.compoundName,
        report.casId,
        report.lambdaMax,
        report.solvent,
        report.source,
        report.generatedByName,
        report.generatedByUserId,
        report.owner.fullName,
        report.owner.userId,
        ...getDateSearchTerms(report.generatedAt),
        ...getDateSearchTerms(report.createdAt),
        getReportAnalysis(report)
      ].some((value) => String(value).toLowerCase().includes(normalizedQuery));
    });
  }, [deferredProjectQuery, deferredQuery, reports, selectedProjectKey]);

  useEffect(() => {
    if (!selectedProjectKey) return;
    if (projectOptions.length === 0) return;
    const matchingProject = projectOptions.find((project) => projectMatchesKey(project, selectedProjectKey));
    if (!matchingProject) {
      setSelectedProjectKey('');
      return;
    }

    if (matchingProject.key !== selectedProjectKey) {
      setSelectedProjectKey(matchingProject.key);
      setProjectQuery(matchingProject.label);
    }
  }, [projectOptions, selectedProjectKey]);

  const logReportExport = async (payload: ReportExportAuditPayload) => {
    try {
      const response = await fetch('/api/audit/report-exports', {
        method: 'POST',
        credentials: 'include',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        console.warn(`Failed to record PDF export audit log: ${response.status}`);
      }
    } catch (auditError) {
      console.warn('Failed to record PDF export audit log:', auditError);
    }
  };

  const exportStoredReport = async (report: StoredReport) => {
    setActiveReportId(report.id);

    try {
      await logReportExport(report);
      openPrintableReport(report, language);
    } finally {
      setActiveReportId(null);
    }
  };

  return (
    <div className="min-w-0 max-w-full overflow-x-hidden space-y-8 sm:space-y-10">
      <div className="flex flex-col xl:flex-row xl:items-end justify-between gap-6">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-[10px] font-mono text-secondary uppercase tracking-[0.4em] font-bold">{text.history}</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-display font-bold text-white tracking-tight">{text.title}</h1>
          <p className="text-white/40 mt-1 max-w-3xl text-sm leading-relaxed">
            {text.description}{' '}
            {currentUser.role === 'admin' ? text.adminScope : text.userScope}
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-[minmax(0,1fr)_minmax(220px,280px)] gap-3 w-full xl:w-[720px]">
          <div className="relative group">
            <Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-white/25 group-focus-within:text-primary transition-colors" />
            <input
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder={text.searchPlaceholder}
              className="w-full rounded-2xl bg-white/[0.03] border border-white/10 pl-12 pr-4 py-4 text-sm text-white outline-none transition-all focus:border-primary/30 focus:bg-white/[0.06]"
            />
          </div>

          <div className="relative group">
            <FolderOpen size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-white/25 group-focus-within:text-primary transition-colors" />
            <input
              value={projectQuery}
              onChange={(event) => {
                setProjectQuery(event.target.value);
                setSelectedProjectKey('');
              }}
              placeholder={text.selectProject}
              className="w-full rounded-2xl bg-white/[0.03] border border-white/10 pl-12 pr-4 py-4 text-sm text-white outline-none transition-all focus:border-primary/30 focus:bg-white/[0.06]"
            />
          </div>
        </div>
      </div>

      {!isLoading && !error && filteredProjectOptions.length > 0 && (
        <div className="min-w-0 max-w-full grid grid-flow-col auto-cols-[minmax(220px,260px)] sm:auto-cols-[minmax(240px,280px)] gap-4 overflow-x-auto overflow-y-hidden custom-scrollbar pb-2">
          {filteredProjectOptions.map((project) => {
            const isSelected = selectedProjectKey === project.key;

            return (
              <button
                key={project.key}
                type="button"
                onClick={() => {
                  setSelectedProjectKey(project.key);
                  setProjectQuery(project.label);
                }}
                className={`text-left rounded-2xl border p-4 transition-all ${
                  isSelected
                    ? 'bg-primary/10 border-primary/40 shadow-[0_0_0_1px_rgba(20,184,166,0.16)]'
                    : 'bg-white/[0.025] border-white/8 hover:bg-white/[0.045] hover:border-white/15'
                }`}
              >
                <div className="flex items-center justify-between gap-3">
                  <div className={`p-2.5 rounded-xl ${isSelected ? 'bg-primary/15 text-primary' : 'bg-white/[0.04] text-white/45'}`}>
                    <FolderOpen size={18} />
                  </div>
                  <span className="text-[10px] font-mono text-white/35 uppercase tracking-widest">
                    {project.reports} {text.reports}
                  </span>
                </div>
                <p className="mt-4 text-white font-semibold truncate">{project.label}</p>
                <p className="mt-1 text-xs text-white/35">{text.lastResult} {formatDateTime(project.lastReportAt)}</p>
              </button>
            );
          })}
        </div>
      )}

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        {isLoading && (
          <div className="xl:col-span-2 glass-panel rounded-2xl p-6 text-sm text-white/55 border-white/10">
            {text.loading}
          </div>
        )}

        {!isLoading && error && (
          <div className="xl:col-span-2 rounded-2xl border border-red-400/20 bg-red-500/10 p-6 text-sm text-red-100">
            {error}
          </div>
        )}

        {!isLoading && !error && reports.length === 0 && (
          <div className="xl:col-span-2 glass-panel rounded-2xl p-6 text-sm text-white/55 border-white/10">
            {text.noReports}
          </div>
        )}

        {!isLoading && !error && reports.length > 0 && !selectedProjectKey && !deferredProjectQuery.trim() && !deferredQuery.trim() && (
          <div className="xl:col-span-2 glass-panel rounded-2xl p-6 text-sm text-white/55 border-white/10">
            {text.selectProjectEmpty}
          </div>
        )}

        {!isLoading && !error && (selectedProjectKey || deferredProjectQuery.trim() || deferredQuery.trim()) && visibleReports.length === 0 && (
          <div className="xl:col-span-2 glass-panel rounded-2xl p-6 text-sm text-white/55 border-white/10">
            {text.noProjectReports}
          </div>
        )}

        {!isLoading && !error && visibleReports.map((report) => {
          const isActive = activeReportId === report.id;
          const project = getReportProject(report);
          const analysis = getReportAnalysis(report);

          return (
            <div
              key={report.id}
              className="glass-panel p-5 sm:p-7 flex flex-col justify-between group hover:border-primary/20 transition-all rounded-2xl relative overflow-hidden"
            >
              <div className="absolute top-0 right-0 w-28 h-28 bg-primary/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 group-hover:bg-primary/10 transition-colors" />

              <div className="space-y-6 relative z-10">
                <div className="flex items-start justify-between gap-4">
                  <div className="p-4 rounded-xl bg-white/[0.03] border border-white/5 text-secondary group-hover:bg-secondary/10 transition-all">
                    <FileText size={24} />
                  </div>
                  <div className="flex shrink-0 gap-2">
                    <button
                      onClick={() => {
                        void exportStoredReport(report);
                      }}
                      disabled={isActive}
                      className="p-2.5 rounded-xl bg-white/[0.03] border border-white/5 text-white/40 hover:text-white hover:bg-white/[0.08] transition-all disabled:opacity-60 disabled:cursor-not-allowed"
                      title={text.printPdf}
                    >
                      <Download size={18} />
                    </button>
                    <button
                      onClick={() => {
                        void exportStoredReport(report);
                      }}
                      disabled={isActive}
                      className="p-2.5 rounded-xl bg-white/[0.03] border border-white/5 text-white/40 hover:text-white hover:bg-white/[0.08] transition-all disabled:opacity-60 disabled:cursor-not-allowed"
                      title={text.openPreview}
                    >
                      <Eye size={18} />
                    </button>
                  </div>
                </div>

                <div>
                  <div className="flex flex-wrap items-center gap-3">
                    <h3 className="text-xl font-display font-bold text-white group-hover:text-primary transition-colors leading-tight">
                      {project.label}
                    </h3>
                  </div>
                  <p className="text-white/55 mt-2 text-sm font-semibold">{analysis}</p>
                  <div className="flex flex-wrap items-center gap-3 mt-3 text-xs">
                    <span className="text-white/45">CAS {report.casId}</span>
                    <span className="w-1 h-1 rounded-full bg-white/10" />
                    <span className="text-primary font-mono uppercase tracking-[0.18em] font-bold">{report.reportId}</span>
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                  <div className="rounded-xl bg-[#0b1121]/50 border border-white/5 p-4">
                    <p className="text-white/30 font-mono uppercase tracking-widest">{text.generatedBy}</p>
                    <p className="text-white mt-2 font-semibold">{report.generatedByName}</p>
                    <p className="text-white/45 text-xs mt-1">@{report.generatedByUserId}</p>
                  </div>
                  <div className="rounded-xl bg-[#0b1121]/50 border border-white/5 p-4">
                    <p className="text-white/30 font-mono uppercase tracking-widest">{text.generatedAt}</p>
                    <p className="text-white mt-2 font-semibold">{formatDateTime(report.generatedAt)}</p>
                  </div>
                  <div className="rounded-xl bg-[#0b1121]/50 border border-white/5 p-4">
                    <p className="text-white/30 font-mono uppercase tracking-widest">{text.absorbance}</p>
                    <p className="text-white mt-2 font-semibold">{formatNumber(report.absorbance)}</p>
                  </div>
                  <div className="rounded-xl bg-[#0b1121]/50 border border-white/5 p-4 sm:col-span-2">
                    <p className="text-white/30 font-mono uppercase tracking-widest">{text.lambdaMax}</p>
                    <p className="text-white mt-2 font-semibold leading-relaxed break-words">{formatWavelengthMax(report.lambdaMax)}</p>
                  </div>
                  <div className="rounded-xl bg-[#0b1121]/50 border border-white/5 p-4 sm:col-span-2">
                    <p className="text-white/30 font-mono uppercase tracking-widest">{text.solvent}</p>
                    <p className="text-white mt-2 font-semibold leading-relaxed break-words">{report.solvent || 'N/A'}</p>
                  </div>
                </div>
              </div>

              <div className="mt-7 pt-5 border-t border-white/[0.05] flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 relative z-10">
                <div className="text-xs text-white/45 leading-relaxed">
                  {text.source} {report.source} - {text.pathLength} {formatNumber(report.pathLengthValue)} cm - {text.concentration} {formatNumber(report.concentrationValue)} mol/L
                </div>
                <div className="text-[10px] font-mono uppercase tracking-[0.24em] text-white/35">
                  {text.stored} {formatDateTime(report.createdAt)}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
